[changelog]
  body = """
{% if version %}## {{ version }}{% else %}## Unreleased{% endif %}{% if date %} - {{ date }}{% endif %}
{% for group, commits in commits | group_by(attribute=\"group\") %}
### {{ group }}
{% for commit in commits %}- {{ commit.message | split(pat=\"\\n\") | first }} ({{ commit.id | truncate(length=7, end=\"\") }})
{% endfor %}
{% endfor %}
"""
  header = "# Changelog\n\n"
  trim = true

[git]
  commit_parsers = [
    { message = "^build", skip = true },
    { message = "^chore", skip = true },
    { message = "^ci", skip = true },
    { message = "^docs", group = "Documentation" },
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactor" },
    { message = "^revert", skip = true },
    { message = "^style", skip = true },
    { message = "^test", skip = true },
  ]
  conventional_commits = true
  filter_unconventional = true
  sort_commits = "oldest"
